### ISSUE TITLE
Modify Portfolio.json to pull holdings data from public addresses

### ISSUE THREAD

**Issue by QuinnMallorry** [christ0ph3r/cryptocurrency-cli#1]
Instead of updating your holdings manually, what if portfolio.json could pull the number of coins in your wallets by watching the public addresses.

I'm going to see if I can get something pulled together next week. This isn't so much an 'issue' rather than a stub for discussion. If anybody has any ideas, I'm open to hear them.

**Comment by christ0ph3r** [comment]
Hey.  It should be an optional if implemented.  It would be a good to allow support for multiple addresses per coin not just a single address.

**Comment by christ0ph3r** [comment]
Actually, a single address is fine.  I am going to close this since its not a bug.  Will happily merge a PR for this if you or someone wants to work on it.
