### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by roccomuso** [christ0ph3r/cryptocurrency-cli#2]
It would be really great if it would automatically refresh, with a configurable interval.
Right now when executed it gets closed, I'd love to see it as a "monitoring" tool that keeps running.

**Comment by christ0ph3r** [comment]
That would be a nice option to have.  I don't have any experience with keeping node refreshed, any suggestions? PR's are welcome.

**Comment by christ0ph3r** [comment]
Closing, you can submit a PR if you want.
