### ISSUE TITLE
Enhancement: show price graph with sparklines

### ISSUE THREAD

**Issue by roccomuso** [christ0ph3r/cryptocurrency-cli#3]
It would be cool to have a little price graph like the one on coinmarketcap using sparklines. ([sparkly](https://github.com/sindresorhus/sparkly))

**Comment by christ0ph3r** [comment]
Coinmarketcap.com does not provide graph data.  Also I am not sure where this would fit as the current table is already big on laptops.

**Comment by christ0ph3r** [comment]
Closing, you can submit a PR if you want.
