### ISSUE TITLE
EUR Version

### ISSUE THREAD

**Issue by jvli0** [christ0ph3r/cryptocurrency-cli#5]
Nice tool! I needed to see data in EUR so here it is in case anybody finds it useful 
https://github.com/jvli0/cryptocurrency-cli/tree/eur

**Comment by christ0ph3r** [comment]
Nice, I will look into adding currency setting soon.

**Comment by christ0ph3r** [comment]
I have added support for many currencies.

https://github.com/christ0ph3r/cryptocurrency-cli/commit/9ec9c97cf7461803e028ea4fb80dcc2fbc24c632

```
npm start -- -c eur
```
